#!/bin/bash
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2014             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.
#
# +------------------------------------------------------------------+
# |                                                                  |
# | cmk_plugin_smart-standby-friendly                                |
# | Check_MK_Agent Plugin "smart" hdd standby / spindown friendly    |
# |                                                                  |
# | Tested with WD RED 8TB (WD80EFAX)                                |
# |                                                                  |
# | Quick'n'dirty edit by Nico Hartung <nicohartung1@googlemail.com> |
# |                                                                  |
# +------------------------------------------------------------------+


if which smartctl > /dev/null 2>&1 ; then

    echo '<<<smart>>>'
    for D in /dev/disk/by-id/{scsi,ata}-*; do

        [ "$D" != "${D%scsi-\*}" ] && continue
        [ "$D" != "${D%ata-\*}" ] && continue
        [ "$D" != "${D%-part*}" ] && continue

        N=$(readlink $D)
        N=${N##*/}

        VEND=$(tr -d ' ' < /sys/block/$N/device/vendor)
        MODEL=$(smartctl --info $D | grep -i "device model" | sed -e "s/.*:[ ]*//g" -e "s/\ /_/g")

        DNAME=${D#/dev/disk/by-id/scsi-}
        DNAME=${DNAME#/dev/disk/by-id/ata-}

        CMD=

        hdparm -C $D | grep -i active > /dev/null 2>&1
        if [ $? -eq 0 ]; then
            CMD=$(smartctl -d ata -v 9,raw48 -A $D > /tmp/cmk-smart_$DNAME)
        else
            #HDDTEMP=$(hddtemp -n $D) > drive is sleeping > doesn't work in standby
            #HDDTEMP=$(hdparm -H $D | grep -i is | awk '{print $5}')
            HDDTEMP=$(echo $(hdparm -H $D | grep -i is | awk '{print $5}'))
            gawk -i inplace -v var1=$HDDTEMP '$2 == "Temperature_Celsius" { $10 = var1 }1' /tmp/cmk-smart_$DNAME
        fi

        cat /tmp/cmk-smart_$DNAME | grep Always | egrep -v '^190(.*)Temperature(.*)' | sed "s|^|$DNAME $VEND $MODEL |"

    done 2>/dev/null

else
    echo "ERROR: smartctl not found" >&2
fi